// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1MoEoRlmz4CJy09YtYZKvMxCcZxG0LM',
    appId: '1:808406711349:web:5771af52a43655f0ac057c',
    messagingSenderId: '808406711349',
    projectId: 'ica13-6ef55',
    authDomain: 'ica13-6ef55.firebaseapp.com',
    storageBucket: 'ica13-6ef55.firebasestorage.app',
    measurementId: 'G-M59P0ZHWX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMI-70cKnNbLlyRD1hV1EN2kYpJfLDOlE',
    appId: '1:808406711349:android:3bd09dc1b8d8aed4ac057c',
    messagingSenderId: '808406711349',
    projectId: 'ica13-6ef55',
    storageBucket: 'ica13-6ef55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYIELq_Lb8sqJuCAQfiAeOrsWE8ZHETGQ',
    appId: '1:808406711349:ios:de00f742d388b4edac057c',
    messagingSenderId: '808406711349',
    projectId: 'ica13-6ef55',
    storageBucket: 'ica13-6ef55.firebasestorage.app',
    iosBundleId: 'com.example.ica13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYIELq_Lb8sqJuCAQfiAeOrsWE8ZHETGQ',
    appId: '1:808406711349:ios:de00f742d388b4edac057c',
    messagingSenderId: '808406711349',
    projectId: 'ica13-6ef55',
    storageBucket: 'ica13-6ef55.firebasestorage.app',
    iosBundleId: 'com.example.ica13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu1MoEoRlmz4CJy09YtYZKvMxCcZxG0LM',
    appId: '1:808406711349:web:11ee9f608093298bac057c',
    messagingSenderId: '808406711349',
    projectId: 'ica13-6ef55',
    authDomain: 'ica13-6ef55.firebaseapp.com',
    storageBucket: 'ica13-6ef55.firebasestorage.app',
    measurementId: 'G-GHX2G0HFDT',
  );
}
